syntax = "proto3";

import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

package grpc.proto.test;

option go_package = "example/7.grpc/pb";

enum Status {
  STATUS_UNSPECIFIED = 0;
  STATUS_ACTIVE = 1;
  STATUS_INACTIVE = 2;
}

message User{
  int64 age = 1;
  int32 gender = 2;
  string name = 3;
  Status status = 4;
  google.protobuf.StringValue hobby = 5;
  google.protobuf.Timestamp createdAt = 6;
  google.protobuf.Timestamp updatedAt = 7;
}

message UserReq {
  int64 id = 1;
}

service UserSvc{
  rpc GetUserInfo(UserReq) returns (User);
}


